# Generated by Django 4.2.7 on 2023-11-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
