# Generated by Django 4.2.7 on 2023-11-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_formentry_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='name',
            field=models.CharField(error_messages={'required': 'Please enter a value for the text field.'}, max_length=100),
        ),
    ]
