# Generated by Django 4.2.7 on 2023-11-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_alter_formentry_dob_alter_formentry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='dob',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
