# Generated by Django 4.2.7 on 2023-11-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_alter_formentry_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='dob',
            field=models.DateField(),
        ),
    ]
